"""Evidence-led theme selection with differentiated expression modes."""
from __future__ import annotations

from collections import defaultdict
from typing import Dict, Iterable, List

from .config import SEMANTIC_SUPPORT_THRESHOLDS, SUPPORT_VALUE
from .models import Claim
from .semantics import theme_label

SINGLE_THEME_PROFILES = {
    "pt": {
        "purpose": {"constructive": "alinhar direção pessoal e escolhas que tenham significado", "defensive": "buscar uma missão perfeita para não precisar experimentar caminhos provisórios", "excessive": "transformar direção em cobrança permanente de coerência", "underdeveloped": "deixar expectativas externas decidirem o rumo por inércia", "integrated": "tratar propósito como direção revisável, confirmada por escolhas e experiência", "lived_example": "aceitar um projeto-piloto que ensine algo real, em vez de esperar certeza total sobre a vocação"},
        "creativity": {"constructive": "dar forma própria a ideias, prazer e expressão", "defensive": "usar desempenho criativo para procurar aprovação", "excessive": "exigir originalidade constante e perder espontaneidade", "underdeveloped": "adiar expressão por medo de exposição ou imperfeição", "integrated": "alternar brincadeira, técnica, risco e descanso sem confundir criação com valor pessoal", "lived_example": "mostrar uma versão ainda imperfeita de algo criado e usar a resposta como informação, não como veredito"},
        "competence": {"constructive": "construir domínio por prática, limites e responsabilidade", "defensive": "usar preparação infinita para evitar avaliação ou vulnerabilidade", "excessive": "converter padrão de qualidade em rigidez e autocobrança", "underdeveloped": "abandonar estrutura antes que a repetição produza habilidade", "integrated": "definir critérios realistas, aprender com erro e reconhecer progresso acumulado", "lived_example": "entregar uma versão suficientemente boa no prazo e anotar o que será melhorado na próxima rodada"},
        "care": {"constructive": "perceber necessidades e responder com presença e limites", "defensive": "cuidar para controlar o vínculo ou evitar pedir ajuda", "excessive": "assumir responsabilidade emocional que pertence a outras pessoas", "underdeveloped": "minimizar necessidades até que apareçam como sobrecarga", "integrated": "combinar acolhimento, autorregulação, reciprocidade e pedido direto", "lived_example": "perguntar se a outra pessoa quer escuta ou solução antes de assumir o problema como seu"},
        "ambition": {"constructive": "transformar desejo de contribuição em metas, responsabilidade e visibilidade", "defensive": "usar conquista para se proteger de dúvida ou comparação", "excessive": "subordinar descanso e vínculos a métricas de realização", "underdeveloped": "reduzir a própria contribuição para evitar exposição", "integrated": "escolher metas sustentáveis e distinguir reconhecimento externo de valor interno", "lived_example": "aceitar mais visibilidade para um trabalho sem transformar cada resposta externa em medida do próprio valor"},
        "pleasure": {"constructive": "reconhecer valores, desejo, beleza e capacidade de receber", "defensive": "buscar conforto para evitar conflito ou decisão", "excessive": "usar gratificação imediata sem considerar consequência ou reciprocidade", "underdeveloped": "tratar prazer como algo que precisa ser merecido", "integrated": "negociar desejo, limites, recursos e cuidado com o corpo e com o vínculo", "lived_example": "reservar tempo ou dinheiro para algo prazeroso depois de verificar o limite real, sem culpa nem impulso"},
        "transformation": {"constructive": "encarar mudanças profundas com honestidade, agência e tempo de elaboração", "defensive": "intensificar situações para sentir controle ou certeza", "excessive": "interpretar toda tensão como prova de crise ou ruptura", "underdeveloped": "preservar estruturas esgotadas para evitar perda e ambivalência", "integrated": "distinguir o que precisa terminar, o que pode ser reparado e o que merece continuidade", "lived_example": "diante de um impasse, separar a conversa difícil, o limite necessário e a decisão irreversível em etapas distintas"},
        "power": {"constructive": "usar influência, desejo e capacidade de decisão com responsabilidade", "defensive": "controlar informação ou ritmo para reduzir insegurança", "excessive": "confundir intensidade com autoridade ou verdade", "underdeveloped": "ceder agência e depois ressentir a escolha", "integrated": "nomear interesses, negociar poder e aceitar limites de controle", "lived_example": "dizer o que quer numa negociação e perguntar o que a outra parte precisa, sem recorrer a silêncio estratégico"},
        "service": {"constructive": "traduzir intenção em prática útil, rotina e contribuição", "defensive": "manter-se ocupado para evitar prioridades emocionais ou decisões maiores", "excessive": "medir valor pessoal apenas por produtividade e utilidade", "underdeveloped": "esperar motivação perfeita antes de criar consistência", "integrated": "desenhar rotinas ajustáveis que sustentem trabalho, cuidado cotidiano e descanso", "lived_example": "reduzir uma rotina ambiciosa a duas práticas sustentáveis que ainda funcionem numa semana difícil"},
        "spirituality": {"constructive": "cultivar imaginação, sentido, contemplação e abertura ao mistério", "defensive": "usar idealização para escapar de limite, evidência ou conflito", "excessive": "tratar intuição como certeza que dispensa verificação", "underdeveloped": "descartar experiências subjetivas por não serem imediatamente mensuráveis", "integrated": "combinar sensibilidade, discernimento, prática e contato com a realidade", "lived_example": "registrar uma impressão intuitiva e depois compará-la com fatos e consequências antes de decidir"},
        "curiosity": {"constructive": "investigar, conectar ideias e formular perguntas melhores", "defensive": "acumular informação para adiar posição ou decisão", "excessive": "fragmentar atenção entre possibilidades sem aprofundamento", "underdeveloped": "repetir explicações conhecidas para evitar revisão de perspectiva", "integrated": "alternar exploração, síntese, comunicação e checagem", "lived_example": "definir uma pergunta, limitar a pesquisa e produzir uma conclusão provisória que possa ser revisada"},
        "order": {"constructive": "criar sequência, clareza e critérios que facilitem ação", "defensive": "organizar detalhes para evitar incerteza que não pode ser eliminada", "excessive": "transformar método em controle rígido", "underdeveloped": "deixar decisões acumularem até parecerem maiores do que são", "integrated": "usar estrutura suficiente e revisá-la quando o contexto mudar", "lived_example": "escolher três critérios para uma decisão e parar de adicionar regras quando eles já distinguem as opções"},
    },
    "en": {
        "purpose": {"constructive": "align personal direction with choices that carry meaning", "defensive": "search for a perfect mission to avoid trying provisional paths", "excessive": "turn direction into a permanent demand for consistency", "underdeveloped": "let outside expectations choose the direction by default", "integrated": "treat purpose as a revisable direction confirmed through choices and experience", "lived_example": "accept a pilot project that teaches something real instead of waiting for total certainty about vocation"},
        "creativity": {"constructive": "give ideas, pleasure and expression a form that feels your own", "defensive": "use creative performance to secure approval", "excessive": "demand constant originality and lose spontaneity", "underdeveloped": "delay expression for fear of exposure or imperfection", "integrated": "alternate play, technique, risk and rest without confusing creation with personal worth", "lived_example": "show an unfinished version of something you made and treat the response as information, not a verdict"},
        "competence": {"constructive": "build mastery through practice, limits and responsibility", "defensive": "prepare indefinitely to avoid evaluation or vulnerability", "excessive": "turn standards into rigidity and relentless self-criticism", "underdeveloped": "leave structure before repetition has time to build skill", "integrated": "set realistic criteria, learn from error and recognize accumulated progress", "lived_example": "deliver a good-enough version on time and record what belongs in the next iteration"},
        "care": {"constructive": "notice needs and respond with presence and limits", "defensive": "provide care to control connection or avoid asking for help", "excessive": "take responsibility for emotions that belong to someone else", "underdeveloped": "minimize needs until they surface as overload", "integrated": "combine warmth, self-regulation, reciprocity and direct requests", "lived_example": "ask whether someone wants listening or solutions before taking their problem on as your own"},
        "ambition": {"constructive": "translate the wish to contribute into goals, responsibility and visibility", "defensive": "use achievement as protection from doubt or comparison", "excessive": "subordinate rest and relationships to measures of achievement", "underdeveloped": "make your contribution smaller to avoid exposure", "integrated": "choose sustainable goals and separate external recognition from internal worth", "lived_example": "accept more visibility for your work without making every response a measure of your worth"},
        "pleasure": {"constructive": "recognize values, desire, beauty and the capacity to receive", "defensive": "seek comfort to avoid conflict or a decision", "excessive": "choose immediate gratification without considering consequence or reciprocity", "underdeveloped": "treat pleasure as something that must be earned", "integrated": "negotiate desire, limits, resources and care for body and relationship", "lived_example": "make room for something enjoyable after checking the real limit, without guilt or impulse"},
        "transformation": {"constructive": "face deep change with honesty, agency and time to process", "defensive": "intensify a situation to regain control or certainty", "excessive": "treat every tension as proof of crisis or rupture", "underdeveloped": "preserve an exhausted structure to avoid loss and ambivalence", "integrated": "distinguish what needs to end, what can be repaired and what deserves continuity", "lived_example": "at an impasse, separate the difficult conversation, the necessary boundary and the irreversible decision into distinct steps"},
        "power": {"constructive": "use influence, desire and decision-making capacity responsibly", "defensive": "control information or pace to reduce insecurity", "excessive": "confuse intensity with authority or truth", "underdeveloped": "give away agency and later resent the choice", "integrated": "name interests, negotiate power and accept the limits of control", "lived_example": "state what you want in a negotiation and ask what the other party needs without using strategic silence"},
        "service": {"constructive": "translate intention into useful practice, routine and contribution", "defensive": "stay busy to avoid emotional priorities or larger decisions", "excessive": "measure personal worth only through productivity and usefulness", "underdeveloped": "wait for perfect motivation before creating consistency", "integrated": "design adjustable routines that support work, everyday care and rest", "lived_example": "reduce an ambitious routine to two sustainable practices that still work during a difficult week"},
        "spirituality": {"constructive": "cultivate imagination, meaning, contemplation and openness to mystery", "defensive": "use idealization to escape limits, evidence or conflict", "excessive": "treat intuition as certainty that needs no verification", "underdeveloped": "dismiss subjective experience because it cannot be measured immediately", "integrated": "combine sensitivity, discernment, practice and contact with reality", "lived_example": "record an intuitive impression, then compare it with facts and consequences before deciding"},
        "curiosity": {"constructive": "investigate, connect ideas and formulate better questions", "defensive": "accumulate information to postpone a position or decision", "excessive": "split attention among possibilities without going deeper", "underdeveloped": "repeat familiar explanations to avoid revising perspective", "integrated": "alternate exploration, synthesis, communication and checking", "lived_example": "define one question, limit the research and produce a provisional conclusion that can be revised"},
        "order": {"constructive": "create sequence, clarity and criteria that make action easier", "defensive": "organize details to avoid uncertainty that cannot be eliminated", "excessive": "turn method into rigid control", "underdeveloped": "let decisions accumulate until they feel larger than they are", "integrated": "use enough structure and revise it when context changes", "lived_example": "choose three criteria for a decision and stop adding rules once they distinguish the options"},
    },
}

POLARITY_THEME_PROFILES = {
    "pt": {
        "autonomy_closeness": {"constructive": "criar proximidade sem tratar acesso constante como prova de afeto", "defensive": "afastar-se depois de adaptar-se demais ou pedir garantias quando o espaço parece incerto", "excessive": "transformar distância em proteção ou proximidade em vigilância", "underdeveloped": "deixar necessidades de contato e espaço implícitas até surgir frustração", "integrated": "nomear o ritmo de contato e de autonomia antes da saturação e renegociá-lo sem punição", "lived_example": "depois de dias de contato intenso, pedir uma noite tranquila em vez de desaparecer"},
        "stability_change": {"constructive": "preservar o que funciona enquanto atualiza o que ficou rígido", "defensive": "adiar a mudança até a pressão forçar uma ruptura ou mudar tudo de uma vez", "excessive": "confundir constância com imobilidade ou novidade com progresso", "underdeveloped": "reagir ao contexto sem criar continuidade suficiente para avaliar resultados", "integrated": "testar mudanças em escala segura, manter critérios e decidir com base no que realmente melhora", "lived_example": "experimentar uma nova rotina por duas semanas antes de abandonar toda a estrutura anterior"},
        "visibility_privacy": {"constructive": "escolher quando aparecer e quando proteger elaboração e intimidade", "defensive": "expor-se para garantir reconhecimento ou esconder-se para evitar avaliação", "excessive": "tornar tudo público ou manter contribuição e necessidade invisíveis", "underdeveloped": "não distinguir discrição escolhida de medo de ocupar espaço", "integrated": "definir o que precisa de audiência, o que precisa de maturação e quem pode ter acesso", "lived_example": "compartilhar o resultado de um trabalho e preservar o processo ainda frágil até ele ganhar forma"},
        "control_spontaneity": {"constructive": "usar planejamento para sustentar ação sem eliminar improviso", "defensive": "controlar cada variável ou agir abruptamente para escapar da sensação de restrição", "excessive": "planejar até paralisar ou improvisar sem assumir consequência", "underdeveloped": "esperar que o contexto decida quando agir e quando parar", "integrated": "definir limites não negociáveis e deixar liberdade dentro deles", "lived_example": "preparar tempo, orçamento e limite de risco, deixando o conteúdo do dia aberto à descoberta"},
        "security_exploration": {"constructive": "usar base e curiosidade como recursos complementares", "defensive": "tratar novidade como ameaça ou usar novidade para não construir base", "excessive": "acumular segurança sem viver ou expandir sem margem para consequências", "underdeveloped": "alternar cautela e impulso sem explicitar o risco aceitável", "integrated": "definir o que precisa estar protegido e qual parte pode ser usada para experimentar", "lived_example": "reservar uma margem de tempo ou dinheiro e usar apenas a parcela excedente para testar uma mudança"},
        "reason_feeling": {"constructive": "usar emoção como dado e pensamento como ferramenta de organização", "defensive": "racionalizar para não sentir ou transformar emoção momentânea em conclusão", "excessive": "analisar até perder contato com a necessidade ou decidir apenas pela intensidade do momento", "underdeveloped": "não traduzir sensação em linguagem verificável e pedido concreto", "integrated": "nomear o que sente, separar fato de interpretação e só então escolher uma resposta", "lived_example": "antes de responder a uma mensagem difícil, escrever o fato, a emoção, a hipótese e o pedido"},
        "receptivity_initiative": {"constructive": "perceber o contexto e agir no momento em que a ação acrescenta algo", "defensive": "esperar sinais indefinidamente ou avançar sem escutar resposta e limite", "excessive": "absorver tudo sem posicionamento ou transformar impulso em urgência", "underdeveloped": "não reconhecer quando é hora de receber e quando é hora de iniciar", "integrated": "alternar escuta, decisão, ação e verificação do efeito", "lived_example": "fazer uma proposta clara e depois abrir espaço real para a resposta, sem pressionar nem retirar a proposta"},
        "individuality_belonging": {"constructive": "participar sem apagar diferenças e afirmar singularidade sem romper pertencimento", "defensive": "adaptar-se para garantir aceitação ou diferenciar-se apenas por oposição", "excessive": "usar o grupo como identidade total ou tratar toda influência como perda de autenticidade", "underdeveloped": "não escolher conscientemente a quais vínculos e valores coletivos quer responder", "integrated": "explicitar valores próprios, reconhecer interdependência e escolher comunidades onde a diferença possa existir", "lived_example": "discordar de um grupo importante sem transformar a discordância numa prova de rejeição"},
    },
    "en": {
        "autonomy_closeness": {"constructive": "build closeness without treating constant access as proof of care", "defensive": "withdraw after adapting too much or seek reassurance when space feels uncertain", "excessive": "turn distance into protection or closeness into monitoring", "underdeveloped": "leave needs for contact and space implicit until frustration builds", "integrated": "state the desired rhythm of contact and autonomy before saturation and renegotiate it without punishment", "lived_example": "after several intense days of contact, ask for a quiet evening instead of disappearing"},
        "stability_change": {"constructive": "preserve what works while updating what has become rigid", "defensive": "delay change until pressure forces rupture or change everything at once", "excessive": "confuse consistency with immobility or novelty with progress", "underdeveloped": "react to context without enough continuity to evaluate results", "integrated": "test change at a safe scale, keep criteria and decide from what actually improves", "lived_example": "try a new routine for two weeks before discarding the entire previous structure"},
        "visibility_privacy": {"constructive": "choose when to be seen and when to protect intimacy and work in progress", "defensive": "seek exposure for reassurance or hide to avoid evaluation", "excessive": "make everything public or keep contribution and need invisible", "underdeveloped": "fail to distinguish chosen privacy from fear of taking up space", "integrated": "decide what needs an audience, what needs more time and who should have access", "lived_example": "share the outcome of a piece of work while protecting the still-fragile process that produced it"},
        "control_spontaneity": {"constructive": "use planning to support action without eliminating improvisation", "defensive": "control every variable or act abruptly to escape restriction", "excessive": "plan until action stops or improvise without owning consequences", "underdeveloped": "wait for circumstances to decide when to act and when to stop", "integrated": "set non-negotiable limits and leave freedom inside them", "lived_example": "prepare time, budget and risk limits while leaving the day's content open to discovery"},
        "security_exploration": {"constructive": "use a stable base and curiosity as complementary resources", "defensive": "treat novelty as a threat or use novelty to avoid building a base", "excessive": "accumulate security without living or expand without margin for consequences", "underdeveloped": "alternate caution and impulse without naming acceptable risk", "integrated": "define what must be protected and which part can be used for experiment", "lived_example": "reserve a margin of time or money and use only the surplus to test a change"},
        "reason_feeling": {"constructive": "use emotion as data and thought as a tool for organization", "defensive": "rationalize to avoid feeling or turn a passing emotion into a conclusion", "excessive": "analyze until the need disappears or decide only from the moment's intensity", "underdeveloped": "fail to translate sensation into checkable language and a concrete request", "integrated": "name the feeling, separate fact from interpretation and then choose a response", "lived_example": "before answering a difficult message, write down the fact, emotion, hypothesis and request"},
        "receptivity_initiative": {"constructive": "read the context and act when action can add something", "defensive": "wait indefinitely for signals or push ahead without listening for response and limits", "excessive": "absorb everything without a position or turn impulse into urgency", "underdeveloped": "miss when it is time to receive and when it is time to initiate", "integrated": "alternate listening, decision, action and checking the effect", "lived_example": "make a clear proposal and then leave real room for the answer without pressure or withdrawal"},
        "individuality_belonging": {"constructive": "participate without erasing difference and assert individuality without discarding belonging", "defensive": "adapt to secure acceptance or differ only through opposition", "excessive": "use the group as a total identity or treat every influence as loss of authenticity", "underdeveloped": "avoid consciously choosing which bonds and shared values deserve a response", "integrated": "state personal values, recognize interdependence and choose communities where difference can exist", "lived_example": "disagree with an important group without turning disagreement into proof of rejection"},
    },
}


def _expression_profile(theme: str, label: str, lang: str) -> Dict[str, str]:
    if theme in POLARITY_THEME_PROFILES[lang]:
        return dict(POLARITY_THEME_PROFILES[lang][theme])
    if theme in SINGLE_THEME_PROFILES[lang]:
        return dict(SINGLE_THEME_PROFILES[lang][theme])
    if lang == "pt":
        return {
            "constructive": f"desenvolver {label} com contexto, prática e limites claros",
            "defensive": f"usar {label} para evitar vulnerabilidade ou incerteza",
            "excessive": f"transformar {label} em exigência rígida ou identidade única",
            "underdeveloped": f"adiar experiências que pedem participação consciente em {label}",
            "integrated": f"tratar {label} como capacidade treinável, sem exigir perfeição nem usá-la para explicar tudo",
            "lived_example": f"observar uma escolha concreta em que {label} altera a resposta e registrar o resultado",
        }
    return {
        "constructive": f"develop {label} through context, practice and clear boundaries",
        "defensive": f"use {label} to avoid vulnerability or uncertainty",
        "excessive": f"turn {label} into a rigid demand or single identity",
        "underdeveloped": f"defer experiences that require conscious engagement with {label}",
        "integrated": f"treat {label} as a trainable capacity without demanding perfection or using it to explain everything",
        "lived_example": f"observe one concrete choice in which {label} changes the response and record the result",
    }


def synthesize_themes(claims: Iterable[Claim], language: str = "pt-BR") -> List[Dict[str, object]]:
    """Aggregate independent evidence families without pretending to probability."""
    lang = "pt" if language.startswith("pt") else "en"
    buckets: Dict[str, List[Claim]] = defaultdict(list)
    for claim in claims:
        if claim.status == "allowed":
            buckets[claim.theme].append(claim)
    themes: List[Dict[str, object]] = []
    for theme, items in buckets.items():
        seen_families = set()
        support = 0
        evidence: List[str] = []
        counterweights: List[str] = []
        claim_ids: List[str] = []
        examples: List[str] = []
        for item in sorted(items, key=lambda claim: (-SUPPORT_VALUE[claim.astrological_support], claim.id)):
            unique = [family for family in item.evidence_families if family not in seen_families]
            if not unique:
                continue
            seen_families.update(unique)
            support += SUPPORT_VALUE[item.astrological_support]
            evidence.extend(item.evidence)
            counterweights.extend(item.counterweights)
            claim_ids.append(item.id)
            examples.extend(item.allowed_examples)
        if not support:
            continue
        level = "strong" if support >= SEMANTIC_SUPPORT_THRESHOLDS["strong"] and len(seen_families) >= 2 else "moderate" if support >= SEMANTIC_SUPPORT_THRESHOLDS["moderate"] else "light"
        label = theme_label(theme, language)
        expression_profile = _expression_profile(theme, label, lang)
        themes.append({
            "id": theme, "label": label, "support_level": level,
            "claim_ids": claim_ids, "evidence": list(dict.fromkeys(evidence)),
            "evidence_families": sorted(seen_families), "counterweights": list(dict.fromkeys(counterweights)),
            "expressions": expression_profile, "examples": list(dict.fromkeys(examples))[:3],
            "lived_examples": [expression_profile["lived_example"]],
            "alternative_expression": "A expressão concreta depende de escolhas, contexto e desenvolvimento." if lang == "pt" else "Concrete expression depends on choices, context and development.",
        })
    rank = {"strong": 3, "moderate": 2, "light": 1}
    return sorted(themes, key=lambda item: (-rank[item["support_level"]], -len(item["evidence_families"]), item["id"]))
